schema_version = "1.0.0"

id = "SmartScene_Toolkit"
version = "1.3.0"
name = "SmartScene Toolkit"
tagline = "Toolkit for smarter parent, hierarchy, mirror operations"
maintainer = "Tianle Yuan"

type = "add-on"

website = "https://github.com/yuantianle/SmartScene_Toolkit-Jun2025"

tags = ["Object", "Scene"]

blender_version_min = "4.4.3"

copyright = ["2025 Tianle Yuan"]

license = [
  "SPDX:GPL-3.0-or-later",
]